name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Optional: Manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or whatever version you use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint pytest

    - name: Lint with Black
      run: |
        black --check .

    - name: Lint with Pylint
      run: |
        pylint main.py  # change this if you have more files

    - name: Run tests with pytest
      run: |
        pytest  # optional, if you have tests
